### PR TITLE
Fix issue #454

### PR DESCRIPTION
**Pull request by mraron**
These changes seem to fix the issue.

### CODE REVIEW

**Comment by mraron** [comment]
Oh sorry I'm stupid, I should edit the migrations, right?

**Comment by luksan47** [comment]
> Oh sorry I'm stupid, I should edit the migrations, right?

Not at all, your PR seems to fix the #454. Or what's on your mind?

**Comment by mraron** [comment]
Oh okay, the comment on top of `Models/PrintAccountHistory.php` made me question myself but now I think I understand.

**Review by luksan47 — APPROVED** [review]
> Oh okay, the comment on top of Models/PrintAccountHistory.php made me question myself but now I think I understand.

Great! If you still have questions/doubts, feel free to ask.

**Pull request merged**
