### PR TITLE
enable multiline buttons

### PR DESCRIPTION
**Pull request by kdmnk**
If the text does not fit in, there can be multiline buttons.
Not nice, so we should try to avoid it, but we cannot test these for all translations and resolutions.
Also this would not solve the problem if one word is too long individually.

### CODE REVIEW

**Review by luksan47 — CHANGES_REQUESTED** [review]
This now messes with the tables, these look really bad.

Screenshot 2020-10-09 at 20 53 38

**Comment by kdmnk** [comment]
> This now messes with the tables, these look really bad.

I can add a new `fixed-size` class that we can add to these buttons. I can't think anything better now.

**Comment by luksan47** [comment]
Is this issue worth that much work?

**Comment by kdmnk** [comment]
How many places does this occur? (the bug that you mentioned)

**Comment by kdmnk** [comment]
I renamed the branch, I will recreate this issue...

**Comment by kdmnk** [comment]
https://github.com/luksan47/mars/pull/451

**Pull request closed without merging**
