### PR TITLE
Issue #14: Printing module: implement free pages functionality

### PR DESCRIPTION
**Pull request by steakhal**
Implements the following:
- Admin can add/remove *free pages* from a user by ID
- Hungarian and English translations for the UI
- Handles validation errors correctly (unlike `modify_balance`)
- Prints the available free pages for the logged in user besides the available money.
- Implements the controller function handling the request.

### CODE REVIEW

**Comment by luksan47** [comment]
Just a comment:
Because of the free pages issue inconsistency, let's just rename the PR to #14, it would look better.

**Comment by steakhal** [comment]
I think the `Issue #x #y #z: Printing module: implement free pages functionality` would be even better.
Which issues should I mention in the Commit message? Which are related?

**Comment by luksan47** [comment]
I would go with only #14 and close the other two as "duplicate". How this sounds?

**Comment by steakhal** [comment]
> I would go with only #14 and close the other two as "duplicate". How this sounds?

Ok.

**Pull request merged**
