### PR TITLE
WIP: Issue #68: Search-user

### PR DESCRIPTION
**Pull request by katkodominik**
Added bootstrap live search.

Any ideas for this? 
> ```css
> ```css
> .bootstrap-select > select.bs-select-hidden, select.bs-select-hidden, select.selectpicker {
>     display: none !important;
> }
> ```
> 
> 
> The select element is there, but hidden. Some CSS magic marks it display: none !important, which is sad in this case. We have to find a solution to style it properly.
> ```
original conversation here: https://github.com/luksan47/mars/issues/68

### CODE REVIEW

**Comment by steakhal** [comment]
Might related: https://stackoverflow.com/questions/34954785/bootstrap-select-didnt-show-on-page-load

**Comment by vendi95** [comment]
Fix the branch before PR, please. Clean up the unnecessary files and make the select working.

**Comment by steakhal** [comment]
> Fix the branch before PR, please. Clean up the unnecessary files and make the select working.

Intermediate commits does not matter much, since we do squash-rebase merging.
The only negative side-affect is that we relay on the GC for collecting the unreferenced files.

I think its OK for now, later on don't commit unnecessary files blindly -- or at least do it on your own fork.

**Comment by steakhal** [comment]
To complete this feature you should:
- Make sure that `select` html element works properly.
- Fills the options of the select with the actual username, id mappings.
- Testing the features that this select inter-cooperates well with them.

It would be great to get familiar with using Bootstrap.

**Comment by luksan47** [comment]
You need 2 things to make the selectpicker work:

1. Include jQuery ( see in #66 [here](https://github.com/luksan47/mars/blob/c4913301f343c3ba75c7918a627227f437054584/resources/views/layouts/app.blade.php#L14) )
2. Initialize selectpicker after the page loads, by adding this script:

```
<script>
    $(document).ready(function() {
        $('.selectpicker').selectpicker();
    });
</script>
```

**Comment by katkodominik** [comment]
solved in new branch, issue #81

**Pull request closed without merging**
